### ISSUE TITLE
The DNS error in narwhal webpage.

### ISSUE THREAD

**Issue by dannluciano** [280north/narwhal#25] opened 2011-11-05 17:32 UTC
In the http://narwhaljs.org/ the github error page is show.

Page does not exist!

Please fix the problem.

**Comment by mathiasbynens** [comment] 2013-06-10 20:16
Duplicate of #29.

**Comment by Krinkle** [comment] 2013-12-18 18:53
Still down :)

**Comment by tlrobinson** [comment] 2013-12-18 19:06
I don't think we have control over the domain any more, and the project is
pretty much dead anyway :-/

**Closed as completed** 2020-01-15 13:38 UTC
